### PR TITLE
Fix build for Linux 4.20

### PR DESCRIPTION
**Pull request by vilkoz**
Fixed following error while building on linux version 4.20.3
```
darling/src/lkm/osfmk/duct/duct_machine_rtclock.c:78:9: error: implicit declaration of function ‘get_monotonic_boottime’; did you mean ‘getboottime’? [-Werror=implicit-function-declaration]
         get_monotonic_boottime (&ltimespec);
         ^~~~~~~~~~~~~~~~~~~~~~
         getboottime
```
```
darling/src/lkm/darling/pthread_kill.c: In function ‘pthread_kill_trap’:
darling/src/lkm/darling/pthread_kill.c:65:17: error: passing argument 1 of ‘clear_siginfo’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   clear_siginfo(&info);
                 ^~~~~
In file included from ./include/linux/syscalls.h:76,
                 from darling/src/lkm/osfmk/duct/duct.h:73,
                 from darling/src/lkm/darling/pthread_kill.h:22,
                 from darling/src/lkm/darling/pthread_kill.c:20:
./include/linux/signal.h:20:52: note: expected ‘kernel_siginfo_t *’ {aka ‘struct kernel_siginfo *’} but argument is of type ‘struct siginfo *’
 static inline void clear_siginfo(kernel_siginfo_t *info)
                                  ~~~~~~~~~~~~~~~~~~^~~~
darling/src/lkm/darling/pthread_kill.c:74:33: error: passing argument 2 of ‘send_sig_info’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   ret = send_sig_info(args.sig, &info, t);
```

### CODE REVIEW

**Comment by vilkoz** [comment]
> Why is casting to `void *` the right thing to do?

Actually it isn't right, but it was the simplest solution.
I've found that according to following patch: https://github.com/torvalds/linux/commit/ae7795bc6187a15ec51cf258abae656a625f9980 the `struct kernel_siginfo` should be used instead `struct siginfo`. I've updated my patch accordingly.

> The indentation is off, here and below

Fixed

**Comment by bugaevc** [comment]
Thanks! LGTM now; but I'm not a kernel developer — it's up to @LubosD to merge this

**Comment by andyneff** [comment]
This is an issue in the newest Fedora 29 kernel too (4.20.14)

**Comment by andyneff** [comment]
Just verified this builds and starts a shell in Fedora 29 Kernel 4.20.14-200 ! 👍

**Pull request merged**
