### PR TITLE
removing generated *.s files, which should not have been committed in…

### PR DESCRIPTION
**Pull request by HinTak**
… the first place

### CODE REVIEW

**Comment by LubosD** [comment]
What makes you think these are generated?

**Comment by HinTak** [comment]
They are removed after "make lkm"

**Comment by HinTak** [comment]
I mean they are removed after "make lkm_clean" (and you can do "make lkm" again too), which clearly indicates that they are not used nor needed.

**Comment by LubosD** [comment]
As long as these files exist in upstream XNU distribution, they should not be removed, because it would make updating to newer XNU harder.

**Comment by HinTak** [comment]
An alternative would be to "fix" `make lkm_clean` so they are not deleted. Anyway, I think the correct approach is to delete them if they are not used/needed, to cut down clutter - it makes life easier on maintaining, when there are fewer files! It is not hard to delete them again after upgrading to a newer XNU - you'll need to re-apply other accumulated changes anyway.

**Comment by facekapow** [comment]
I think neither approach is correct:
1. If the files are present in Apple's code, I think we should keep them (even if we don't use them).
2. We can't fix `lkm_clean` to not delete them because the code that deletes them is the Linux kernel's build system, thinking that the lowercase `.s` files are auto-generated assembly files that have been preprocessed.

Honestly, I think this is just a non-issue.

**Comment by CuriousTommy** [comment]
This PR will be closed since we are currently in the process of archiving this repo (Darling no longer uses the kernel module).

**Pull request closed without merging**
